project:
  type: website

website:
  title: "Blitz the Gap"
  navbar:
    left:
      - href: index.qmd
        text: Challenges
      - href: tutorial.qmd
        text: LDP Workflow example

format:
  html:
    theme:
      - yeti
      - brand
    css: styles.css
    toc: true

editor: visual

