project:
  type: website

website:
  title: "Blitz the Gap"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Challenges
      - href: workflows.qmd
        text: Workflows

format:
  html:
    theme: yeti
    css: styles.css
    toc: true
    grid:
      margin-width: 0px