project:
  type: website

website:
  title: "Blitz the Gap"
  search: false
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: workflows.qmd
        text: Workflows

format:
  html:
    theme: yeti
    embed-resources: true
    smooth-scroll: true
    toc: true
    grid:
      margin-width: 0px